const { withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const NETWORK_SECURITY_CONFIG_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withCleartextLoopback.js - do not edit by hand, edit that file instead. -->
<network-security-config>
    <!-- The native torrent-stream module serves downloaded pieces to ExoPlayer over
         plain http://127.0.0.1 (see modules/torrent-stream/.../StreamHttpServer.kt) -
         loopback-only, never leaves the device. Android blocks cleartext traffic by
         default on targetSdk 28+ in release builds, so without this exception P2P
         playback silently fails with ERR_CLEARTEXT_NOT_PERMITTED in production while
         working fine in dev. Everything else keeps the platform default (HTTPS-only).
    -->
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">127.0.0.1</domain>
    </domain-config>
</network-security-config>
`;

// Release-only manifest overlay - mirrors how the RN/Expo template itself grants
// blanket cleartext in android/app/src/debug/AndroidManifest.xml (which already makes
// debug builds work fine). Scoping this to src/release/ instead of src/main/ matters:
// once ANY networkSecurityConfig is present, Android ignores usesCleartextTraffic
// entirely for that variant - putting this in src/main/ would merge into debug too and
// override the template's already-permissive debug config with this stricter
// loopback-only one, silently breaking anything else in debug that relies on cleartext
// (Metro/dev tooling). Keeping it release-only leaves debug untouched.
const RELEASE_MANIFEST_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withCleartextLoopback.js - do not edit by hand, edit that file instead. -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application android:networkSecurityConfig="@xml/network_security_config" />
</manifest>
`;

function withCleartextLoopback(config) {
  return withDangerousMod(config, [
    'android',
    async (config) => {
      const appRoot = config.modRequest.platformProjectRoot + '/app';

      const xmlDir = path.join(appRoot, 'src/main/res/xml');
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, 'network_security_config.xml'), NETWORK_SECURITY_CONFIG_XML);

      const releaseManifestDir = path.join(appRoot, 'src/release');
      fs.mkdirSync(releaseManifestDir, { recursive: true });
      fs.writeFileSync(path.join(releaseManifestDir, 'AndroidManifest.xml'), RELEASE_MANIFEST_XML);

      return config;
    },
  ]);
}

module.exports = withCleartextLoopback;
