const { withAppBuildGradle, withProjectBuildGradle } = require('expo/config-plugins');
const { mergeContents } = require('@expo/config-plugins/build/utils/generateCode');

const MEDIA3_VERSION = '1.9.0';
// Jellyfin's FFmpeg audio-decoder extension — needed so codecs without a
// hardware/platform decoder (E-AC3, DTS, etc. common in WEB-DL MKVs) still
// produce audio instead of playing video with silent/missing sound. Verified
// current release via Maven Central (org.jellyfin.media3:media3-ffmpeg-decoder).
// NOTE: this artifact is GPLv3-licensed — fine for personal/sideloaded use,
// reconsider before any store distribution.
const FFMPEG_DECODER_VERSION = '1.9.0+1';
// buildscript{} evaluates before expo-root-project sets rootProject.ext.kotlinVersion,
// so that variable isn't reachable here — pin explicitly and keep in sync with the
// Kotlin version Expo's prebuild output reports ("kotlin: X.Y.Z" during Configure).
const COMPOSE_COMPILER_KOTLIN_VERSION = '2.1.20';

/**
 * `android/app/build.gradle` and `android/build.gradle` are regenerated by
 * `expo prebuild`, so the Compose compiler plugin classpath + media3
 * (ExoPlayer) dependencies the native player needs must be injected here
 * rather than hand-edited, same reasoning as withVideoPlayerActivity.js.
 */
function withNativePlayerGradle(config) {
  config = withProjectBuildGradle(config, (config) => {
    config.modResults.contents = mergeContents({
      tag: 'native-player-compose-classpath',
      src: config.modResults.contents,
      newSrc:
        `    classpath("org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin:${COMPOSE_COMPILER_KOTLIN_VERSION}")`,
      anchor: /classpath\('org\.jetbrains\.kotlin:kotlin-gradle-plugin'\)/,
      offset: 1,
      comment: '//',
    }).contents;
    return config;
  });

  return withAppBuildGradle(config, (config) => {
    let contents = config.modResults.contents;

    contents = mergeContents({
      tag: 'native-player-compose-plugin',
      src: contents,
      newSrc: 'apply plugin: "org.jetbrains.kotlin.plugin.compose"',
      anchor: /^apply plugin: "com\.facebook\.react"/m,
      offset: 1,
      comment: '//',
    }).contents;

    contents = mergeContents({
      tag: 'native-player-buildfeatures',
      src: contents,
      newSrc: '    buildFeatures {\n        compose true\n    }',
      anchor: /^android\s*\{/m,
      offset: 1,
      comment: '//',
    }).contents;

    contents = mergeContents({
      tag: 'native-player-deps',
      src: contents,
      newSrc:
        `    implementation("androidx.activity:activity-compose:1.9.2")\n` +
        `    implementation(platform("androidx.compose:compose-bom:2024.09.02"))\n` +
        `    implementation("androidx.compose.ui:ui")\n` +
        `    implementation("androidx.compose.foundation:foundation")\n` +
        `    implementation("androidx.compose.material3:material3")\n` +
        `    implementation("androidx.compose.material:material-icons-extended")\n` +
        `    implementation("androidx.compose.animation:animation")\n` +
        `    implementation("androidx.media3:media3-exoplayer:${MEDIA3_VERSION}")\n` +
        `    implementation("androidx.media3:media3-ui:${MEDIA3_VERSION}")\n` +
        `    implementation("androidx.media3:media3-common:${MEDIA3_VERSION}")\n` +
        `    implementation("androidx.media3:media3-session:${MEDIA3_VERSION}")\n` +
        `    implementation("org.jellyfin.media3:media3-ffmpeg-decoder:${FFMPEG_DECODER_VERSION}")`,
      anchor: /^dependencies\s*\{/m,
      offset: 1,
      comment: '//',
    }).contents;

    config.modResults.contents = contents;
    return config;
  });
}

module.exports = withNativePlayerGradle;
