const { withMainApplication, mergeContents } = require('expo/config-plugins');

/**
 * Registers NativePlayerPackage (android/app/src/main/java/.../player/NativePlayerModule.kt
 * + NativePlayerPackage.kt) in MainApplication.kt's PackageList, since that file
 * is regenerated by `expo prebuild` and any hand-edit is wiped on the next run.
 * Uses mergeContents' tagged-comment markers so reruns are idempotent.
 */
function withNativePlayerPackage(config) {
  return withMainApplication(config, (config) => {
    let contents = config.modResults.contents;

    contents = mergeContents({
      tag: 'native-player-package-import',
      src: contents,
      newSrc: 'import com.tdandroid.app.player.NativePlayerPackage',
      anchor: /^import expo\.modules\.ExpoReactHostFactory/m,
      offset: 1,
      comment: '//',
    }).contents;

    contents = mergeContents({
      tag: 'native-player-package-register',
      src: contents,
      newSrc: '          add(NativePlayerPackage())',
      anchor: /PackageList\(this\)\.packages\.apply\s*\{/,
      offset: 1,
      comment: '//',
    }).contents;

    config.modResults.contents = contents;
    return config;
  });
}

module.exports = withNativePlayerPackage;
