const { withAndroidManifest, withAndroidStyles } = require('expo/config-plugins');

/**
 * Registers the native video player (PlayerActivity) that replaces
 * react-native-video for playback — see src/hooks/player/useNativePlayerBridge.ts
 * for the JS side. Both android/app/src/main/java/.../MainApplication.kt and
 * the manifest are regenerated by `expo prebuild`, so this registration must
 * be codified as a plugin (mirrors plugins/withAndroidTVBanner.js) rather than
 * hand-edited, or it's silently wiped on the next prebuild.
 *
 * launchMode is deliberately NOT singleTask/singleInstance and exported is
 * false — it's launched only via an explicit Intent from NativePlayerModule,
 * never as an entry point, and finishing it naturally reveals the live
 * MainActivity/RN screen underneath (MainActivity itself is singleTask; two
 * singleTask activities in the same task would fight each other).
 */
function withVideoPlayerActivity(config) {
  config = withAndroidManifest(config, (config) => {
    const manifest = config.modResults;
    const app = manifest.manifest.application?.[0];
    if (!app) return config;

    app.activity = app.activity || [];
    const exists = app.activity.some((a) => a.$['android:name'] === '.player.PlayerActivity');
    if (!exists) {
      app.activity.push({
        $: {
          'android:name': '.player.PlayerActivity',
          'android:theme': '@style/PlayerTheme',
          'android:launchMode': 'singleTop',
          'android:supportsPictureInPicture': 'true',
          'android:screenOrientation': 'sensorLandscape',
          'android:configChanges': 'screenSize|orientation|keyboardHidden|uiMode|density|screenLayout',
          'android:exported': 'false',
        },
      });
    }

    return config;
  });

  config = withAndroidStyles(config, (config) => {
    const styles = config.modResults;
    styles.resources.style = styles.resources.style || [];
    const exists = styles.resources.style.some((s) => s.$.name === 'PlayerTheme');
    if (!exists) {
      styles.resources.style.push({
        $: { name: 'PlayerTheme', parent: 'Theme.AppCompat.NoActionBar' },
        item: [
          { $: { name: 'android:windowBackground' }, _: '@android:color/black' },
          { $: { name: 'android:statusBarColor' }, _: '@android:color/black' },
          { $: { name: 'android:navigationBarColor' }, _: '@android:color/black' },
          { $: { name: 'android:windowFullscreen' }, _: 'true' },
          { $: { name: 'android:windowContentOverlay' }, _: '@null' },
        ],
      });
    }
    return config;
  });

  return config;
}

module.exports = withVideoPlayerActivity;
